
export const GUJARAT_DISTRICTS = [
  { en: "Ahmedabad", gu: "અમદાવાદ" },
  { en: "Amreli", gu: "અમરેલી" },
  { en: "Anand", gu: "આણંદ" },
  { en: "Aravalli", gu: "અરવલ્લી" },
  { en: "Banaskantha", gu: "બનાસકાંઠા" },
  { en: "Bharuch", gu: "ભરૂચ" },
  { en: "Bhavnagar", gu: "ભાવનગર" },
  { en: "Botad", gu: "બોટાદ" },
  { en: "Chhota Udepur", gu: "છોટા ઉદેપુર" },
  { en: "Dahod", gu: "દાહોદ" },
  { en: "Dang", gu: "ડાંગ" },
  { en: "Devbhoomi Dwarka", gu: "દેવભૂમિ દ્વારકા" },
  { en: "Gandhinagar", gu: "ગાંધીનગર" },
  { en: "Gir Somnath", gu: "ગીર સોમનાથ" },
  { en: "Jamnagar", gu: "જામનગર" },
  { en: "Junagadh", gu: "જૂનાગઢ" },
  { en: "Kheda", gu: "ખેડા" },
  { en: "Kutch", gu: "કચ્છ" },
  { en: "Mahisagar", gu: "મહિસાગર" },
  { en: "Mehsana", gu: "મહેસાણા" },
  { en: "Morbi", gu: "મોરબી" },
  { en: "Narmada", gu: "નર્મદા" },
  { en: "Navsari", gu: "નવસારી" },
  { en: "Panchmahal", gu: "પંચમહાલ" },
  { en: "Patan", gu: "પાટણ" },
  { en: "Porbandar", gu: "પોરબંદર" },
  { en: "Rajkot", gu: "રાજકોટ" },
  { en: "Sabarkantha", gu: "સાબરકાંઠા" },
  { en: "Surat", gu: "સુરત" },
  { en: "Surendranagar", gu: "સુરેન્દ્રનગર" },
  { en: "Tapi", gu: "તાપી" },
  { en: "Vadodara", gu: "વડોદરા" },
  { en: "Valsad", gu: "વલસાડ" }
];
